name: Test
on:
  pull_request:
    branches:
      - develop
      - master
    path-ignores:
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Package Install 
        run: npm install

      - name: Tests
        run: npm test

      - name: Build
        run: npm run build
